#/appspec.yml
# CodeDeploy에서 배포 관련 설정
version: 0.0
os: linux # os는 배포하는 EC2 Instance가 Linux 계열이면 linux로, Windows 서버 인스턴스라면 windows로 설정
files: # files는 빌드 파일 중 source를 destination에 복사시킨다는 의미입니다.
  - source: /
    destination: /home/ubuntu/build
hooks:
  BeforeInstall:
    - location: scripts/npm-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
  ValidateService:
    - location: scripts/healthCheck.sh
      timeout: 300
      runas: ubuntu
      # ubuntu의 $HOME 환경변수를 이용해보려고 runas ubuntu