version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
      - npm install -g forever
      - pwd
    run-as: root

artifacts:
  files:
    - "**/*"
cache:
  paths:
    - "node_modules/**/*"